export function successPage(sessionId: string): string {
  const safeSession = sessionId.replace(/[^A-Za-z0-9_\-]/g, "");
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>NEXUS Purchase Complete</title><style>
:root{color-scheme:dark;--bg:#070B15;--panel:#0D1320;--purple:#6E5AF6;--accent:#8671F6;--text:#F5F5F7;--muted:#A0A7B9}
*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at 70% 20%,rgba(110,90,246,.18),transparent 35%),var(--bg);font:16px Inter,Segoe UI,sans-serif;color:var(--text);padding:24px}.card{width:min(580px,100%);background:rgba(13,19,32,.95);border:1px solid rgba(134,113,246,.25);border-radius:22px;padding:32px;box-shadow:0 24px 80px rgba(0,0,0,.35)}.mark{width:56px;height:56px;border-radius:16px;display:grid;place-items:center;background:linear-gradient(135deg,#4D35E5,#8671F6);font-weight:800;font-size:24px}h1{margin:20px 0 10px;font-size:30px}p{color:var(--muted);line-height:1.6}label{display:block;margin:24px 0 8px;font-weight:600}input{width:100%;padding:14px 16px;border-radius:12px;border:1px solid rgba(134,113,246,.3);background:#080d17;color:var(--text);font-size:16px}button{width:100%;margin-top:14px;padding:14px 18px;border:0;border-radius:12px;background:linear-gradient(135deg,#4D35E5,#8671F6);color:white;font-weight:700;font-size:16px;cursor:pointer}.result{display:none;margin-top:22px;padding:18px;border:1px solid rgba(134,113,246,.35);border-radius:14px;background:#080d17}.key{font:700 18px ui-monospace,SFMono-Regular,Consolas,monospace;overflow-wrap:anywhere;color:#fff}.error{color:#ffb4b4}.small{font-size:13px}</style></head>
<body><main class="card"><div class="mark">N</div><h1>Payment confirmed</h1><p>Confirm the email used at Stripe checkout to reveal your NEXUS license key.</p><label for="email">Checkout email</label><input id="email" type="email" autocomplete="email" required><button id="reveal" type="button">Reveal license key</button><div id="result" class="result" aria-live="polite"></div><p class="small">Keep your key private. NEXUS support will never ask for your full payment-card information.</p></main>
<script>
const sessionId=${JSON.stringify(safeSession)};const button=document.getElementById('reveal');const result=document.getElementById('result');
button.addEventListener('click',async()=>{button.disabled=true;result.style.display='block';result.textContent='Verifying purchase…';try{const response=await fetch('/v1/order/reveal',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({session_id:sessionId,email:document.getElementById('email').value})});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||'Unable to reveal license.');result.innerHTML='<div class="small">'+(data.license_type==='30_day'?'30-Day License':'Lifetime License')+'</div><div class="key">'+data.license_key+'</div><p class="small">Copy this key into the NEXUS activation screen.</p>';}catch(error){result.innerHTML='<div class="error">'+error.message+'</div>';}finally{button.disabled=false;}});
</script></body></html>`;
}
